### ISSUE TITLE
Bug: driver not closing properly

### ISSUE THREAD

**Issue by reinzor** [iron-ox/fadecandy_ros#8]
```
09.06.20 15:46:08 (+0200)  ros  Traceback (most recent call last):
09.06.20 15:46:08 (+0200)  ros    File "/opt/Eurogroep/melodic/lib/fadecandy_driver/fadecandy_node", line 16, in <module>
09.06.20 15:46:08 (+0200)  ros      main()
09.06.20 15:46:08 (+0200)  ros    File "/opt/Eurogroep/melodic/lib/fadecandy_driver/fadecandy_node", line 11, in main
09.06.20 15:46:08 (+0200)  ros      node = FadecandyNode()
09.06.20 15:46:08 (+0200)  ros    File "/opt/Eurogroep/melodic/lib/python2.7/dist-packages/fadecandy_driver/fadecandy_node.py", line 24, in __init__
09.06.20 15:46:08 (+0200)  ros      self._diagnostic_updater.setHardwareID(self._driver.serial_number)
09.06.20 15:46:08 (+0200)  ros  AttributeError: FadecandyNode instance has no attribute '_driver'
```

Happens sometimes on restart.

**Comment by reinzor** [comment]
This can happen when you close the driver when it is not initialized properly.
